CarAndUser/models/Car.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * Class Car
 * @package app\models
 * @property int $id [int]
 * @property string $model [varchar(55)]
 * @property string $color [varchar(255)]
 * @property int $number_wheels [int]
 * @property int $number_doors [int]
 * @property bool $driver_left [tinyint(1)]
 * @property bool $deleted [tinyint(1)]
 * @property string $created_by [varchar(255)]
 */
class Car extends ActiveRecord
{
    public static function tableName()
    {
        return 'car';
    }

    public function rules()
    {
        return [
            [['model', 'color', 'number_wheels', 'number_doors', 'driver_left'], 'required'],
            [['model', 'color'], 'string'],
            [['number_wheels', 'number_doors'], 'integer'],
            [['driver_left', 'deleted'], 'boolean'],
        ];
    }

    public function getCreator()
    {
        return $this->hasOne(User::class, [
            'id' => 'created_by'
        ]);
    }


}

?>

CarAndUser/controllers/CarController.php
<?php

namespace app\controllers;

use app\models\CarSearchModel;
use app\models\SignupForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Car;

class CarController extends Controller
{
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //$cars = Car::find()->all();
        //return $this->render('index', ['models'=> $cars]);

        $page = 'index';

        $searchModel = new CarSearchModel();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $page);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDeleted()
    {
        // Action for the Deleted button on index page

        //$cars = Car::find()->all();
        //return $this->render('index', ['models'=> $cars]);

        $page = 'deleted';

        $searchModel = new CarSearchModel();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $page);

        return $this->render('deleted', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionUpdate($id){

        $car = Car::findOne(['id'=>$id]);

        $formData = yii::$app->request->post();
        if($car->load($formData)){
            if($car->save()){
                yii::$app->session->setFlash('message','Your car has been added to the database.');
                return $this->redirect(['index']);
            }
            else{
                yii::$app->session->setFlash('error','Something went wrong.');
            }
        }
        return $this->render('update', ['car' => $car]);
    }

    public function actionCreate(){
        $car = new Car();
        $formData = yii::$app->request->post();
        if (yii::$app->user->isGuest) {
            $username = 'Not Available';
        } else{
            $username = yii::$app->user->identity->username;
        }

        if($car->load($formData)){
            $car->created_by = $username;
            if($car->save()){
                yii::$app->session->setFlash('message','Your car has been added to the database.');
                return $this->redirect(['index']);
            }
            else{
                yii::$app->session->setFlash('error','Something went wrong.');
            }
        }
        return $this->render('create', ['car' => $car]);
    }

    public function actionView($id){
        return $this->render('view', ['id'=>$id]);
    }

    public function actionDelete($id){
        $car = Car::findOne(['id'=>$id]);
        $deleted = $car->deleted;
        if ($deleted==0) {
            $car->deleted = '1';
            $car->save();
        } elseif($deleted ==1) {
            $car->delete();
        }

        return $this->redirect(['index']);
    }

    public function actionRecover($id){
        $car = Car::findOne(['id'=>$id]);
        $car->deleted = '0';
        $car->save();

        return $this->redirect(['index']);
    }



}

CarAndUser/views/car/_form.php
<?php

use yii\helpers\html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $car app\models\Car */

$form = ActiveForm::begin()
?>
<div class="row">
    <div class="form-group">
        <div class="col-lg-6">
            <?= $form->field($car, 'model'); ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-lg-6">
            <?php $items = ['red' => 'red', 'orange' => 'orange', 'yellow' => 'yellow',
                'green' => 'green', 'blue' => 'blue', 'purple' => 'purple',
                'black' => 'black', 'white' => 'white', 'grey' => 'grey',]; ?>
            <?= $form->field($car, 'color')->dropDownList($items, ['prompt' => 'Choose a color...']); ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-lg-6">
            <?= $form->field($car, 'number_wheels')->textInput()->label('number of wheels'); ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-lg-6">
            <?= $form->field($car, 'number_doors')->textInput()->label('number of doors'); ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-lg-6">
            <?= $form->field($car, 'driver_left')->checkbox([
                'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            ]) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-lg-6">
            <div class="col-lg-3">
                <?php if ($this->title == 'Create') {
                    echo Html::submitButton('Create', ['class' => 'btn btn-primary']);
                } elseif($this->title == 'Update') {
                    echo Html::submitButton('Update', ['class' => 'btn btn-primary']);
                }
                ?>
            </div>
            <div class="col-lg-2">
                <!--<a href=<?php echo yii::$app->homeURL; ?> class="btn btn-primary" >Home</a> -->
                <span style="margin-bottom: 20px;"><?= Html::a('Home', ['car/index'], ['class' => 'btn btn-primary'])?></span>
            </div>
        </div>
    </div>
</div>


<?php
$form = ActiveForm::end()
?>

CarAndUser/views/car/create.php
<?php
use yii\helpers\html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $car app\models\Car */

$this->title = 'Create';

?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Add your car to the database</h1>
    </div>

    <div class="body-content">
        <?= $this->render('_form',['car'=>$car], ['view.php' => $this->title]) ?>
    </div>

</div>

CarAndUser/views/car/deleted.php
<?php
use yii\helpers\html;
/* @var $this yii\web\View */
/* @var $models \app\models\Car[] */


$this->title = 'Cars in the database';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1 style="color: #337ab7;">Deleted cars</h1>

        <p class="lead">View, delete or recover your deleted car.</p>

    </div>


    <div class="body-content">

        <div class="row">
            <?php
            //$dataProvider = new \yii\data\ArrayDataProvider([
            //   'allModels'=>$models,
            //    'key'=>'id',
            //    'pagination'=>[
            //            'pageSize'=>10
            //    ]
            //]);

            echo \yii\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    'id',            // title attribute (in plain text)
                    [
                            'attribute' => 'model',
                            'value' => 'model'
                    ],
                    [
                        'attribute' => 'color',
                        'value' => 'color'
                    ],
                    [
                        'attribute' => 'number_wheels',
                        'value' => 'number_wheels'
                    ],
                    [
                        'attribute' => 'number_doors',
                        'value' => 'number_doors'
                    ],
                    [
                            'attribute'=>'driver_left',
                            'value'=>function($model){
                                /* @var $model \app\models\Car */
                                if($model->driver_left==1){
                                    return Yii::t('app','Left');
                                }
                                return Yii::t('app','Right');
                            }
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {delete} {reset} ',
                        'buttons' => [
                                'reset' => function($url, $model, $key) {
                                    return Html::a('Recover', ['recover', 'id'=>$model->id]);
                                },
                        ],
                    ],
                ],
            ]);
            ?>
        </div>


        <div>
            <span style="margin-bottom: 20px;"><?= Html::a('Home', ['car/index'], ['class' => 'btn btn-primary'])?></span>
        </div>

    </div>
</div>

CarAndUser/views/car/index.php
<?php
use yii\helpers\html;
/* @var $this yii\web\View */
/* @var $models \app\models\Car[] */

$filter_number_doors = array();
for($i=0;$i<=20;$i++){
    $filter_number_doors[$i] = $i;
}


$this->title = 'Cars in the database';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1 style="color: #337ab7;">Cars in the database</h1>

        <p class="lead">Create, view, update or delete cars in the database.</p>

    </div>

    <div>
        <span style="margin-bottom: 20px;"><?= Html::a('Create', ['car/create'], ['class' => 'btn btn-primary'])?></span>
    </div>


    <div class="body-content">

        <div class="row">
            <?php
            //$dataProvider = new \yii\data\ArrayDataProvider([
            //   'allModels'=>$models,
            //    'key'=>'id',
            //    'pagination'=>[
            //            'pageSize'=>10
            //    ]
            //]);

            echo \yii\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    'id',            // title attribute (in plain text)
                    [
                            'attribute' => 'model',
                            'value' => 'model'
                    ],
                    [
                        'attribute' => 'color',
                        'value' => 'color'
                    ],
                    [
                        'attribute' => 'number_wheels',
                        'value' => 'number_wheels'
                    ],
                    [
                        'attribute' => 'number_doors',
                        'value' => 'number_doors',
                        'filter'=>$filter_number_doors,
                    ],
                    [
                            'attribute'=>'driver_left',
                            'value'=>function($model){
                                /* @var $model \app\models\Car */
                                if($model->driver_left==1){
                                    return Yii::t('app','Left');
                                }
                                return Yii::t('app','Right');
                            },
                            'filter'=>['1'=>'Left', '0'=>'Right'],
                    ],
                    [
                        'attribute' => 'creator.id',
                        'value'=>'creator.username',
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {update} {delete} ',
                    ],

                ],
            ]);
            ?>
        </div>

        <div>
            <span style="margin-bottom: 20px;"><?= Html::a('Deleted', ['car/deleted'], ['class' => 'btn btn-primary'])?></span>
        </div>

    </div>
</div>

CarAndUser/views/car/update.php
<?php
use yii\helpers\html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $car app\models\Car */

$this->title = 'Update';

?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Add your car to the database</h1>
    </div>

    <div class="body-content">
        <?= $this->render('_form',['car'=>$car], ['view.php' => $this->title]) ?>
    </div>

</div>

CarAndUser/views/car/view.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $car \frontend\models\ContactForm */

use app\models\Car;
use common\models\User;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\widgets\DetailView;

$this->title = 'View';
$this->params['breadcrumbs'][] = $this->title;

$car = Car::findOne(['id'=>$id]);
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>


    <div class="row">
        <div class="col-lg-5">
            <?php
            echo DetailView::widget([
                'model' => $car,
                'attributes' => [
                    'model',            // title attribute (in plain text)
                    [                      // the owner name of the model
                        'label' => 'Color',
                        'value' => $car->color,
                    ],
                    'number_wheels',
                    'number_doors',
                    [                      // the owner name of the model
                        'label' => 'Driver Seat',
                        'value'=>function($model){
                            /* @var $model \app\models\Car */
                            if($model->driver_left==1){
                                return Yii::t('app','Left');
                            }
                            return Yii::t('app','Right');
                        },
                    ],
                ],
            ]);
            ?>

        </div>
    </div>


    <div class="col-lg-2">
        <!--<a href=<?php echo yii::$app->homeURL; ?> class="btn btn-primary" >Home</a> -->
        <span style="margin-bottom: 20px;"><?= Html::a('Home', ['car/index'], ['class' => 'btn btn-primary'])?></span>
    </div>
</div>